# Generated by Django 2.2 on 2019-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
