# Generated by Django 2.2 on 2019-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='trusted',
            new_name='is_trust',
        ),
        migrations.AddField(
            model_name='job',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
